name: Build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  memory:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [ubuntu-24.04, ubuntu-22.04-arm]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Build
      run: |
        make -f build.mk
        
        #- name: Upload
      #uses: actions/upload-artifact@v4
        #with:
        #name: foonathan-memory-${{ matrix.platform }}
          #path: *.deb

    - name: Deploy
      run: |
        codename=$(lsb_release -c -s)
        git clone --depth 1 https://x-access-token:${{ secrets.TOKEN }}@github.com/alest-software/ubuntu.git
        for fn in *.deb; do
          arch=$(dpkg --info ${fn} | awk '/Architecture:/ {print $2}')
          fname=$(basename ${fn})
          dest="dists/$codename/main/binary-$arch"
          mkdir -p "ubuntu/${dest}"
          cp "${fn}" "ubuntu/${dest}/${fname}"
          (cd ubuntu; git add "${dest}/${fname}")
        done
        cd ubuntu
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -m 'Automatic deployment' || echo 'Nothing to commit'
        git push
